-- MySQL Script generated by MySQL Workbench
-- Thu Jan  3 18:33:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PMach
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PMach
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PMach` DEFAULT CHARACTER SET utf8 ;
USE `PMach` ;

-- -----------------------------------------------------
-- Table `PMach`.`BENHNHAN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PMach`.`BENHNHAN` (
  `IDBN` INT NOT NULL AUTO_INCREMENT,
  `TenBN` VARCHAR(100) NULL,
  `GioiTinh` INT NULL,
  `NamSinh` DATE NULL,
  `DiaChi` VARCHAR(100) NULL,
  PRIMARY KEY (`IDBN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PMach`.`THUOC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PMach`.`THUOC` (
  `IDThuoc` INT NOT NULL AUTO_INCREMENT,
  `TenThuoc` VARCHAR(45) NULL,
  `DonVi` VARCHAR(45) NULL,
  `Gia` VARCHAR(100) NULL,
  PRIMARY KEY (`IDThuoc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PMach`.`DONTHUOC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PMach`.`DONTHUOC` (
  `IDDT` INT NOT NULL AUTO_INCREMENT,
  `DonVi` VARCHAR(45) NULL,
  `SoLuong` INT NULL,
  `CachDung` VARCHAR(100) NULL,
  `Gia` INT NULL,
  `THUOC_IDThuoc` INT NOT NULL,
  PRIMARY KEY (`IDDT`),
  INDEX `fk_DONTHUOC_THUOC1_idx` (`THUOC_IDThuoc` ASC) VISIBLE,
  CONSTRAINT `fk_DONTHUOC_THUOC1`
    FOREIGN KEY (`THUOC_IDThuoc`)
    REFERENCES `PMach`.`THUOC` (`IDThuoc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PMach`.`PHIEUKHAM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PMach`.`PHIEUKHAM` (
  `IDPK` INT NOT NULL AUTO_INCREMENT,
  `NgayKham` DATE NULL,
  `TrieuChung` VARCHAR(100) NULL,
  `ChuanDoan` VARCHAR(100) NULL,
  `IDBN` INT NOT NULL,
  `IDDT` INT NOT NULL,
  PRIMARY KEY (`IDPK`),
  INDEX `fk_PHIEUKHAM_BENHNHAN_idx` (`IDBN` ASC) VISIBLE,
  INDEX `fk_PHIEUKHAM_DONTHUOC1_idx` (`IDDT` ASC) VISIBLE,
  CONSTRAINT `fk_PHIEUKHAM_BENHNHAN`
    FOREIGN KEY (`IDBN`)
    REFERENCES `PMach`.`BENHNHAN` (`IDBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PHIEUKHAM_DONTHUOC1`
    FOREIGN KEY (`IDDT`)
    REFERENCES `PMach`.`DONTHUOC` (`IDDT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PMach`.`HOADON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PMach`.`HOADON` (
  `IDHD` INT NOT NULL AUTO_INCREMENT,
  `NgayKham` DATE NULL,
  `TienKham` INT NULL DEFAULT 300000,
  `TienThuoc` INT NULL,
  `IDPK` INT NOT NULL,
  PRIMARY KEY (`IDHD`),
  INDEX `fk_HOADON_PHIEUKHAM1_idx` (`IDPK` ASC) VISIBLE,
  CONSTRAINT `fk_HOADON_PHIEUKHAM1`
    FOREIGN KEY (`IDPK`)
    REFERENCES `PMach`.`PHIEUKHAM` (`IDPK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PMach`.`BAOCAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PMach`.`BAOCAO` (
  `IDBC` INT NOT NULL AUTO_INCREMENT,
  `NgayKham` DATE NULL,
  `SoBN` INT NULL,
  `DoanhThu` INT NULL,
  PRIMARY KEY (`IDBC`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;